pub mod basic_block;
pub mod dag;
pub mod label;
pub mod operand;
pub mod quadruple;
pub mod tac;
pub mod temp;
pub mod triple;

pub use basic_block::BasicBlock;
pub use dag::Dag;
pub use dag::DagNode;
pub use label::LabelManager;
pub use operand::LabelId;
pub use operand::Operand;
pub use operand::TempId;
pub use quadruple::Quadruple;
pub use quadruple::TacOp;
pub use quadruple::{cse_and_to_triples, cse_quadruples};
pub use tac::TacInstr;
pub use temp::TempManager;
pub use triple::Triple;
pub use triple::TripleRef;
pub use triple::quadruples_to_triples;
